---
title: "demosite"
---

This is a Quarto website.

```{r}
#exploring IPGTT_tidy_data
library(dplyr)
library(readxl)
IPGTT_tidy_data <- read_excel("IPGTT_tidy_data.xlsx")
IPGTT_tidy_final <- IPGTT_tidy_data
oldnames <- names(IPGTT_tidy_data)
colnames(IPGTT_tidy_final) <- c("mouse", "bodyweight", "test_week", "genotype", "sex", "time_point", "glucose_reading")
summary(IPGTT_tidy_final)
unique(IPGTT_tidy_data$Mouse)
unique(IPGTT_tidy_data$BW)
unique(IPGTT_tidy_data$Genotype)
unique(IPGTT_tidy_data$Sex)
```

```{r}
IPGTT_tidy_final %>% filter(mouse != "nan") -> IPGTT_tidy_final
IPGTT_tidy_final %>% filter(mouse != "Mouse") -> IPGTT_tidy_final
IPGTT_tidy_final <- IPGTT_tidy_final %>% filter(!(is.na(bodyweight) & is.na(glucose_reading)))
```

```{r}
library(stringr)
IPGTT_tidy_final$genotype <- factor(IPGTT_tidy_final$genotype, order = TRUE, levels = c("WT-WT","KO-NOD","Het-NOD"))
IPGTT_tidy_final$sex <- factor(IPGTT_tidy_final$sex)
IPGTT_tidy_final %>% mutate(time_point = as.numeric(str_extract(time_point, "\\d+"))) -> IPGTT_tidy_final

IPGTT_tidy_final$mouseid <- paste(IPGTT_tidy_final$mouse,
                                  substring(IPGTT_tidy_final$genotype, 1, 1),
                                  sep = '-')

IPGTT_tidy_final %>% relocate(mouseid, .before = mouse) -> IPGTT_tidy_final
IPGTT_tidy_final %>% relocate(genotype, .before = test_week) -> IPGTT_tidy_final
IPGTT_tidy_final %>% relocate(sex, .before = test_week) -> IPGTT_tidy_final
IPGTT_tidy_final %>% relocate(bodyweight, .before = glucose_reading) -> IPGTT_tidy_final

library(ggplot2)
IPGTT_tidy_final$test_week <- factor(IPGTT_tidy_final$test_week, order = TRUE, levels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12))
```

```{r}
library(dplyr)
library(ggplot2)

okabe_ito_palette <- rep(grDevices::palette.colors(palette = "Okabe-Ito"))

IPGTT_median <- IPGTT_tidy_final %>% 
  filter(test_week %in% 1:4) %>% 
  filter(!is.na(glucose_reading)) %>% 
  group_by(time_point, genotype, test_week) %>% 
  summarize(median_glucose = median(glucose_reading, na.rm = TRUE))

ggplot(IPGTT_tidy_final %>% filter(test_week %in% 1:4, !is.na(glucose_reading )), aes(time_point, glucose_reading, color = genotype, group = mouseid)) + 
  # geom_point() + 
  geom_line(alpha = 0.25) + 
  scale_color_manual(values = okabe_ito_palette) + 
  theme_minimal() + 
  geom_line(data = IPGTT_median, aes(time_point, median_glucose, color = genotype, group = genotype)) + 
  scale_x_continuous(breaks = seq(0, 120, by = 30)) + 
  scale_y_continuous(breaks = seq(0, 800, by = 200)) + 
  facet_wrap(~ test_week, ncol = 4) + 
  theme(legend.position = "bottom") + 
  labs(title = "IPGTT trajectories overlaid within-genotype median", subtitle = "(First four weeks of testing)", x = "Test time (min)", y = "Blood glucose (mg/dL)")
```



